//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.19 at 09:38:13 PM MSK 
//


package topprogersgroup.ws.foreignsystem;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CertificateId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CertificateNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="VeterinaryDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="RegistrationPlace" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IssueDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="LocalCompetentAuthority" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CentralCompetentAuthority" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "certificateId",
    "certificateNumber",
    "veterinaryDocumentNumber",
    "registrationPlace",
    "issueDate",
    "localCompetentAuthority",
    "centralCompetentAuthority"
})
@XmlRootElement(name = "VeterinaryCertificate")
public class VeterinaryCertificate {

    @XmlElement(name = "CertificateId")
    protected int certificateId;
    @XmlElement(name = "CertificateNumber")
    protected int certificateNumber;
    @XmlElement(name = "VeterinaryDocumentNumber")
    protected int veterinaryDocumentNumber;
    @XmlElement(name = "RegistrationPlace", required = true)
    protected String registrationPlace;
    @XmlElement(name = "IssueDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issueDate;
    @XmlElement(name = "LocalCompetentAuthority", required = true)
    protected String localCompetentAuthority;
    @XmlElement(name = "CentralCompetentAuthority", required = true)
    protected String centralCompetentAuthority;

    /**
     * Gets the value of the certificateId property.
     * 
     */
    public int getCertificateId() {
        return certificateId;
    }

    /**
     * Sets the value of the certificateId property.
     * 
     */
    public void setCertificateId(int value) {
        this.certificateId = value;
    }

    /**
     * Gets the value of the certificateNumber property.
     * 
     */
    public int getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * Sets the value of the certificateNumber property.
     * 
     */
    public void setCertificateNumber(int value) {
        this.certificateNumber = value;
    }

    /**
     * Gets the value of the veterinaryDocumentNumber property.
     * 
     */
    public int getVeterinaryDocumentNumber() {
        return veterinaryDocumentNumber;
    }

    /**
     * Sets the value of the veterinaryDocumentNumber property.
     * 
     */
    public void setVeterinaryDocumentNumber(int value) {
        this.veterinaryDocumentNumber = value;
    }

    /**
     * Gets the value of the registrationPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationPlace() {
        return registrationPlace;
    }

    /**
     * Sets the value of the registrationPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationPlace(String value) {
        this.registrationPlace = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDate(XMLGregorianCalendar value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the localCompetentAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalCompetentAuthority() {
        return localCompetentAuthority;
    }

    /**
     * Sets the value of the localCompetentAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalCompetentAuthority(String value) {
        this.localCompetentAuthority = value;
    }

    /**
     * Gets the value of the centralCompetentAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCentralCompetentAuthority() {
        return centralCompetentAuthority;
    }

    /**
     * Sets the value of the centralCompetentAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCentralCompetentAuthority(String value) {
        this.centralCompetentAuthority = value;
    }

}
